# Generated by Django 4.1.2 on 2022-10-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("Image", models.ImageField(upload_to="photos")),
                ("album_id", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("color", models.CharField(blank=True, max_length=8, null=True)),
                ("image_url", models.TextField()),
            ],
        ),
    ]
