# Generated by Django 4.1.2 on 2022-10-20 18:59

from django.db import migrations, models

import api.models.image


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_album_id_image_albumid_alter_image_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[api.models.image.Image.hex_validator],
                verbose_name="dominant color",
            ),
        ),
    ]
